### ISSUE TITLE
New-AzSTenantOfferAndQuotas - BadRequest

### ISSUE THREAD

**Issue by JakobGSvendsen** [Azure/AzureStack-Tools#103]
Trying to create plans and offers on TP3:

PS C:\AzureStack-Tools\ServiceAdmin> New-AzSTenantOfferAndQuotas -tenantID $aadTenant
cmdlet New-AzSTenantOfferAndQuotas at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
VERBOSE: Obtaining token from AAD...
WARNING: Get-AzureStackToken cmdlet will be deprecated in a future release of AzureStackAdmin module.
VERBOSE: Creating quotas...
VERBOSE: Creating resource group for plans and offers...
New-AzureRmResourceGroup : Operation returned an invalid status code 'BadRequest'
At C:\AzureStack-Tools\ServiceAdmin\AzureStack.ServiceAdmin.psm1:44 char:5
+     New-AzureRmResourceGroup -Name $Name -Location $Location -ErrorAc ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmResourceGroup], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupCmdlet
 

It is a newly installed environment. All I did was to install Visual Studio 2015 community edition with azure stack powershell 3.0 and afterwards install azurestack module using
Install-Module -Name AzureStack -RequiredVersion 1.2.8 -Scope CurrentUser

**Comment by markscholman** [comment]
We see an error the same as issue #104 when creating new plans and offers using the tools: 'A parameter cannot be found that matches parameter name 'SubscriptionId'.'

**Comment by MatthewMcGlynn** [comment]
We recently fixed up issues we had with AzureStack module versioning - so it should work alright again. Closing this - but feel free to open another issue if you are still having difficulties.
