### ISSUE TITLE
String Checking in Add-VMImage

### ISSUE THREAD

**Issue by ned1313** [Azure/AzureStack-Tools#107]
The Sku and Title properties in Add-VMImage do not allow for a "." in the string.  Azure does allow a "." as a character.  For instance, the Centos 7.2 image in Azure has a Sku of "7.2" and a Title of "Centos Based 7.2".  I suggest changing the error checking to allow for the period.

**Comment by knithinc** [comment]
Not a relevant issue anymore since this has been replaced with the AzureStack module 1.3.0 version.
