### ISSUE TITLE
 New-Server2016VMImage fails to add market place item because of an updated AzureStack module.

### ISSUE THREAD

**Issue by RuudBorst** [Azure/AzureStack-Tools#108]
Doc: https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-add-default-image

New-Server2016VMImage in https://github.com/Azure/AzureStack-Tools/blob/master/ComputeAdmin/AzureStack.ComputeAdmin.psm1 fails with 'Add-AzureRMGalleryItem : A parameter cannot be found that matches parameter name 'SubscriptionId'." 

Its because the AzureStack module is updated two days ago to 1.2.9: https://www.powershellgallery.com/packages/AzureStack/1.2.9 , the parameters are not there in version 1.2.9 of Add-AzureRMGalleryItem.

Line 268: "Add-AzureRMGalleryItem -SubscriptionId $subscription -GalleryItemUri $galleryItemURI -ApiVersion 2015-04-01"

**Comment by markscholman** [comment]
Use this:
Install-Module -Name AzureRM -RequiredVersion 1.2.8 -Force
Install-Module -Name AzureStack -RequiredVersion 1.2.8 -Force
See issue #104 
Mark

**Comment by RuudBorst** [comment]
Didnt see your issue, I will close this one.
