### ISSUE TITLE
Validator should be catching hard-coded storage endpoint

### ISSUE THREAD

**Issue by JeffGoldner** [Azure/AzureStack-Tools#132]
Many templates in the Azure quickstart have hard-coded blob endpoints. These are not being flagged. See many of the sap* templates.

**Comment by marcvaneijk** [comment]
@JeffGoldner, before closing this item. I believe this capability was added to the validator. Can you confirm?

**Comment by knithinc** [comment]
This is now fixed. Closing issue.
