### ISSUE TITLE
Close-AzSAlert failed in multi-box AzureStack environment

### ISSUE THREAD

**Issue by RobinBao** [Azure/AzureStack-Tools#155]
Command: Close-AzSAlert -AzureStackCredential $cred -TenantID $aadTenant -AlertID "<GUID>" -Environment "AzureStackAdmin"

Failed: Parameter set cannot be resolved using the specified named parameters.

**Comment by RobinBao** [comment]
ParameterSetName='CloseAlert' is inconsistent with other paramters

**Comment by wangshayu** [comment]
I'm working on this issue

**Comment by MatthewMcGlynn** [comment]
#179

**Comment by wangshayu** [comment]
fixed and merged to vnext
