### ISSUE TITLE
Register-AzureStackWithMyDirectoryTenant fails because of multiple refresh tokens.

### ISSUE THREAD

**Issue by RuudBorst** [Azure/AzureStack-Tools#174]
Identity/AzureStack.Identity.psm1

Hi @shriramnat ,

I tried to register my guest Tenant and got the following error: "Register-AzureStackWithMyDirectoryTenant : Cannot process argument transformation on parameter 'RefreshToken'. Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Security.SecureString"."

So I debugged and found out that the $refreshtoken variable populated by "$refreshToken = Get-AzureRmUserRefreshToken $azureEnvironment $azureStackEnvironment.AdTenant" returned multiple "System.Security.SecureString" and thus a System.Object[] instead of the expected one "System.Security.SecureString" by the " Initialize-GraphEnvironment -Environment $graphEnvironment -DirectoryTenantId $DirectoryTenantName -RefreshToken $refreshToken" function.  

In my case the Get-AzureRmUserRefreshToken function using the code below returns multiple tokens. 

$tokens = [Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache]::DefaultShared.ReadItems()
    $refreshToken = $tokens |
        Where Resource -EQ $azureEnvironment.ActiveDirectoryServiceEndpointResourceId |
        Where IsMultipleResourceRefreshToken -EQ $true |
        Where DisplayableId -EQ $azureAccount.Context.Account.Id |
        Select -ExpandProperty RefreshToken |
        ConvertTo-SecureString -AsPlainText -Force

I filtered out and used the token with my directorytenantid in the authority url, https://login.microsoftonline.com/4a206ce8-49e1-4661-b413-0683951594ad/, in my case $Refreshtoken[2]. That allowed me to continue and register the tenant applications. 
This needs to be fixed with a medium priority. Screenshots below.

![screenshot_48](https://cloud.githubusercontent.com/assets/8448592/25329388/d607b17e-28db-11e7-803b-7482cd3d7586.png)
![screenshot_49](https://cloud.githubusercontent.com/assets/8448592/25329391/d7d04e8a-28db-11e7-9cf2-20af6f017288.png)
![screenshot_50](https://cloud.githubusercontent.com/assets/8448592/25329395/d9dabc60-28db-11e7-8a7c-59797d614f68.png)
![screenshot_51](https://cloud.githubusercontent.com/assets/8448592/25329399/db7b4bc0-28db-11e7-81d4-483e6aae8761.png)

**Comment by shriramnat** [comment]
this should be fixed now
