### ISSUE TITLE
Need change the scripts to refer to new infra VM name

### ISSUE THREAD

**Issue by esthermiao** [Azure/AzureStack-Tools#178]
From internal report, 
Installed onenode build 0422.1 
All infra VMs were renamed from MAS-*** to AzS-***. 
Instructions and scripts for connecting to VPN need to be changed.

**Comment by vikasnav** [comment]
Sent a PR for this change

**Comment by MatthewMcGlynn** [comment]
PR #184 was accepted into vnext. Closing. Thanks.
