### ISSUE TITLE
MultiTenancy: Publish-AzureStackApplicationsToARM is broken

### ISSUE THREAD

**Issue by MahendraAgrawal** [Azure/AzureStack-Tools#183]
When try to onboard directory tenant, Publish-AzureStackApplicationsToARM is broken. I showed it to Shri, but before I could capture log/error, environment is gone. I will try on another environment to provide exact error, but repro is fairly simple. just follow the doc here and this is the first call we make to publish and it fails. 
Here is the error:
VERBOSE: GET https://login.windows.net/azurestackci10.onmicrosoft.com/.well-known/openid-configuration with 0-byte payload
VERBOSE: received 1365-byte response of content type application/json; charset=utf-8
Loading identity application data...
WARNING: Skipping registration of Admin application: AdminResourceManager.Azure Stack - Administration
WARNING: Skipping registration of Admin application: AdminPortal.Azure Stack - Portal Administration
WARNING: Skipping registration of Admin application: AdminPolicy.Azure Stack - Policy Administration
WARNING: Skipping registration of Admin application: AdminMonitoring.Azure Stack - Monitoring Administration
VERBOSE: Performing the operation "Creating the resource..." on target "/subscriptions/689b4909-7937-4787-b194-2e142df57d5b/r
esourceGroups/system/providers/Microsoft.Subscriptions.Providers/applicationRegistrations/ResourceManager.Azure%20Stack".
New-AzureRmResource : InvalidRequestContent : The request content was invalid and could not be deserialized: 'Could not 
find member 'directoryRoles' on object of type 'ApplicationRegistrationPropertiesDefinition'. Path 'directoryRoles'.'.
At C:\AzureStack-Tools\AzureStack-Tools-master\Identity\AzureStack.Identity.psm1:394 char:34
+ ... plication = New-AzureRmResource @params -Force -Verbose -ErrorAction  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : InvalidRequestContent,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzur 
   eResourceCmdlet
 

PS C:\AzureStack-Tools\AzureStack-Tools-master>

**Comment by keystroke** [comment]
This should no-longer be required, this was an old temporary workaround from an earlier azure stack build.
