### ISSUE TITLE
Not Supported: VMExtension publisher 'ESET'

### ISSUE THREAD

**Issue by roberto-mardeni** [Azure/AzureStack-Tools#214]
When using the TemplateValidator to validate a template that includes the ESET / FileSecurity VM Extension with a freshly generated CloudCapabilities.json file, the VM Extension is reported as not supported when the template in fact works.

**Comment by marcvaneijk** [comment]
@roberto-mardeni, sorry for the delayed reply. Just to understand is the ESET / FileSecurity VM Extension available in Azure Stack? or are you targeting another cloud in the Azure Platform that has the extension? If you are targeting Azure Stack and the extension does not exists, the report should state the extension as not supported.

**Comment by marcvaneijk** [comment]
Not active. Closing issue
