### ISSUE TITLE
Add-VMSSGallery fails in VNext with error Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'File'. Specified method is not supported..Exception

### ISSUE THREAD

**Issue by MahendraAgrawal** [Azure/AzureStack-Tools#223]
Add-VMSSGallery fails in VNext with error Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'File'. Specified method is not supported..Exception

It works fine on master.

**Comment by BrianLPeterson** [comment]
It looks like this is an error when multiple versions of the module are loaded.  Fix has been submitted to use PSScriptRoot instead of GetModuleBase

**Comment by knithinc** [comment]
Closing this since it appears to be fixed now and we haven't heard back about anymore such failures.
