### ISSUE TITLE
Add-AzsIPPool failed with HTTP status code Conflict

### ISSUE THREAD

**Issue by wangshayu** [Azure/AzureStack-Tools#235]
This cmdlet failed after change to use Add-AzureRmResource, looks like the request body miss something

Add-AzSIPPool -StartIPAddress "192.168.55.1" -EndIPAddress "192.168.55.254" -AddressPrefix "192.168.55.0/24" -Name "testpool" -Region "local"

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://adminmanagement.local.azurestack.external/subscriptions/ec812fc5-cbb2-4709-92f6-4c190dde68c3/resourceGroups/sys
tem.local/providers/Microsoft.Fabric.Admin/fabricLocations/local/IPPools/testpool?api-version=2016-05-01

Headers:
User-Agent                    : AzurePowershell/v1.0.0.0
ParameterSetName              : Resource that resides at the subscription level.
CommandName                   : New-AzureRmResource

Body:
{
  "properties": {
    "EndIpAddress": "192.168.55.254",
    "StartIpAddress": "192.168.55.1",
    "AddressPrefix": "192.168.55.0/24"
  }
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Conflict

Headers:
Pragma                        : no-cache
x-ms-correlation-request-id   : 95b0e25f-dcdf-46c7-89ff-7267746c3933
x-ms-ratelimit-remaining-subscription-writes: 1198
x-ms-request-id               : 95b0e25f-dcdf-46c7-89ff-7267746c3933
x-ms-routing-request-id       : LOCAL:20170622T073441Z:95b0e25f-dcdf-46c7-89ff-7267746c3933
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Date                          : Thu, 22 Jun 2017 07:34:41 GMT
Server                        : Microsoft-HTTPAPI/2.0

Body:

**Comment by wangshayu** [comment]
The old version on master branch works fine

**Comment by troettinger** [comment]
We have identified the bug and work on a solution

**Comment by knithinc** [comment]
This is now fixed I believe. If it isn't please open a new issue.
