### ISSUE TITLE
Test-AzureRMTemplate output string contains incorrect report file path

### ISSUE THREAD

**Issue by wangshayu** [Azure/AzureStack-Tools#237]
This cmdlet output the report file to the default path which should be working directory while in the output message it tells the report file is located at $PSScriptRoot\xxx

      $reportHtml = $title + $validationSummary + $reportXml.OuterXml|Out-String
		ConvertTo-Html  $postContent -head $head -Body $reportHtml | out-File $Report
	}
	$reportFilePath = Join-Path $PSScriptRoot $Report
	Write-Output "Validation Summary:
	`Passed: $passedCount
	`NotSupported: $notSupportedCount
	`Exception: $exceptionCount
	`Warning: $warningCount
	`Recommend: $recommendCount
	`Total Templates: $totalCount"
	Write-Output "Report available at - $reportFilePath"

**Comment by knithinc** [comment]
Fixed.
