### ISSUE TITLE
Need to set GraphAudience for RBAC roles/assignment to work

### ISSUE THREAD

**Issue by wangshayu** [Azure/AzureStack-Tools#253]
1.2.10 Add-AzureRmEnvironment set GraphEndpoint but not GraphResourceId when passing a value to ArmEndpoint.

We need to track the fix to AzureRM module in 1.2.10 and update the document

**Comment by wangshayu** [comment]
The issue in AzureRm repo is https://github.com/Azure/azure-powershell/issues/4254

**Comment by knithinc** [comment]
This is fixed in latest Azure PS.
