### ISSUE TITLE
Horrible UX if you happened to name your computer "AzureStack"

### ISSUE THREAD

**Issue by KirkMunro** [Azure/AzureStack-Tools#295]
I'm facing an issue because I had named my AS computer AzureStack.

During the AS preview phases, I had performed several installations with the base computer named AzureStack without issue. With the release of the Development Kit, it seems this is no longer possible, as the installer fails if your local computer is named AzureStack. The handling of this test is horrible, performed way too late during the install, and the recovery is very difficult if not impossible.

The core issue is this: The Azure Stack installer must perform the bare metal computer name test before actually attempting the install, before gathering networking information, etc. It should fail immediately if the computer name is rejected with appropriate instructions to rename the computer. Otherwise there is no easy way to recover via Rerun.

I have renamed my computer as AzureStackHost, and now I'm attempting to rerun the install. The rerun fails because there is a manifest somewhere that still contains the AzureStack computer name, and as a result all tests against that computer (the old computer name) fail.

In my case, I really don't want to go through the entire redeployment of AzureStack. I want to rerun. Where is the computer name written by the installer (to disk, Registry, etc.)? Once I identify those locations, can I manually change them and then perform a Rerun of the installer? Or do I have no choice but to start from scratch in this case?

**Comment by KirkMunro** [comment]
Sorry to pester you guys, I know it's summer/holiday season and everything, but it would really be helpful if you could point me to the location of the "manifest" (wherever Azure Stack stores the name of the computer used during the install) so that I can manually change it to match the new computer name and then kick-off a ReRun of the installer.

**Comment by knithinc** [comment]
@BrianLPeterson , could you please take a look at this issue?

**Comment by BrianLPeterson** [comment]
"@KirkMunro -  it is highly recommended that you don't edit the configuration information and do a rerun because rerun starts deployment at the last failed step and may other previous steps could have already cached the configuration values such as the domain controller etc.  Changing the configuration values once deployment has started can put your machine in unknown bad states. 

If you made a configuration mistake when deploying please redeploy from a new clean image instead.

**Comment by KirkMunro** [comment]
@BrianLPeterson Fair enough. Thanks for letting me know.

**Comment by marcvaneijk** [comment]
Closing inactive item
