### ISSUE TITLE
Cannot validate argument on parameter 'AadTenantId'. The argument is null. 

### ISSUE THREAD

**Issue by uday31in** [Azure/AzureStack-Tools#30]
VERBOSE: Obtaining token from AAD...
Get-AzureStackToken : Cannot validate argument on parameter 'AadTenantId'. The argument is null. 
Provide a valid value for the argument, and then try running the command again.
At C:\AzureStack-Tools-master\ServiceAdmin\AzureStack.ServiceAdmin.psm1:41 char:150
+ ... eDirectoryServiceEndpointResourceId -AadTenantId $AADTenantID -Creden ...
+                                                      ~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-AzureStackToken], ParameterBindingValidation 
   Exception
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.AzureStack.Commands.Sec 
   urity.GetToken

PS C:\AzureStack-Tools-master> Get-AzureRmEnvironment -Name $AzureEnvironment

Name                                              : AzureStackCloud
EnableAdfsAuthentication                          : False
ActiveDirectoryServiceEndpointResourceId          : https://api.azurestack.local/18408589-bea1-44d6-a5d0-88f0dfc6195f
AdTenant                                          : 
GalleryUrl                                        : https://gallery.azurestack.local/
ManagementPortalUrl                               : 
ServiceManagementUrl                              : 
PublishSettingsFileUrl                            : 
ResourceManagerUrl                                : https://api.azurestack.local/
SqlDatabaseDnsSuffix                              : 
StorageEndpointSuffix                             : 
ActiveDirectoryAuthority                          : https://login.windows.net/<removed>
GraphUrl                                          : https://graph.windows.net/
GraphEndpointResourceId                           : 
TrafficManagerDnsSuffix                           : 
AzureKeyVaultDnsSuffix                            : 
AzureDataLakeStoreFileSystemEndpointSuffix        : 
AzureDataLakeAnalyticsCatalogAndJobEndpointSuffix : 
AzureKeyVaultServiceEndpointResourceId            :

**Comment by MatthewMcGlynn** [comment]
Hey Uday, I am closing this because the AAD tenant should be included as parameter during the addition of the Azure Stack environment. This can be done by using the Connect to Azure Stack module. I would prefer that we use this method of deriving the AAD tenant so that we can optimize the solution in the Connect module and leverage it throughout. Thanks!
