### ISSUE TITLE
AzureStack Tools PowerShell modules

### ISSUE THREAD

**Issue by ConradCahill** [Azure/AzureStack-Tools#300]
I am starting to use the AzureStack tools and noticed that after registering my tools directory as a PSModulePath, PowerShell doesn't recognize any of the modules except the GraphAPI module.  Looking into the directories it is because the .psm1 file names do not match their parent directory names.  For example, AzureStack.Connect.psm1 is in a directory called .\Connect.  A simple change of the directory or nesting the module file in a matching directory name (AzureStack.Connect\AzureStack.Connect.psm1) will allow PowerShell to recognize the modules and automatically expose the functions or allow for simple import by name.

**Comment by MatthewMcGlynn** [comment]
Thanks for the feedback! We are looking at making some directory changes in the future and will consider this at that time.
