### ISSUE TITLE
Creating service principal in a ADFS topology is not working

### ISSUE THREAD

**Issue by frostarun** [Azure/AzureStack-Tools#307]
I followed the steps according to your [docs](https://github.com/Azure/AzureStack-Tools/tree/master/Identity#creating-a-service-principal-in-a-disconnected-ad-fs-topology) ,

Its getting this error ,

> The term 'New-GraphApplicationGroup' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\AzureStack-Tools-master\Identity\AzureStack.Identity.psm1:118 char:5
$output = Invoke-Command -Session $domainAdminSession -ScriptBloc ...

I can't find a module which has the" New-GraphApplicationGroup" function , Any help might be appreciated .

**Comment by frostarun** [comment]
Hi ,  Its done but I cannot get the client secret... can you explain how to get the client secret for the app which we created ?

**Comment by shriramnat** [comment]
Hey @frostarun,
the certificate is created on the local machine that you're running the script from and the thumbprint is returned as an output of this cmdlet. You can pick the cert up from the local cert store
