### ISSUE TITLE
RegisterWithAzure.ps1 : Activate-Bridge: Error : System.Exception: Task: Invocation of interface 'ActivateAzureBridge' of role 'Cloud\Fabric\AzureBridge' failed: 

### ISSUE THREAD

**Issue by lilsaliu** [Azure/AzureStack-Tools#309]

**Comment by lilsaliu** [comment]
STARTING: Task Cloud\Fabric\AzureBridge - ActivateAzureBridge
VERBOSE: Interface: Path to module: C:\CloudDeployment\Classes\AzureBridge\AzureBridge.psm1 - 8/22/2017 1:20:51 AM
VERBOSE: Interface: Running interface ActivateAzureBridge (Classes\AzureBridge\AzureBridge.psm1, AzureBridge:ActivateAzureBridge) - 8/22/201
7 1:20:51 AM
WARNING: [AzureBridge:ActivateAzureBridge] The names of some imported commands from the module 'RoleHelpers' include unapproved verbs that m
ight make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter
. For a list of approved verbs, type Get-Verb. - 8/22/2017 1:20:53 AM
VERBOSE: [AzureBridge:ActivateAzureBridge] ActivateAzureBridgeFeatures : BEGIN on WIN-M4NF69C1R3R as AZURESTACK\AzureStackAdmin - 8/22/2017 
1:20:53 AM
VERBOSE: [AzureBridge:ActivateAzureBridge] Deployment Id: 55543754-eae5-46ad-b212-fc9be93fd7ac - 8/22/2017 1:20:54 AM
VERBOSE: [AzureBridge:ActivateAzureBridge] Azure Stack AAD directoryTenantID: 5454420b-2e38-4b9e-8b56-1712d321cf33 - 8/22/2017 1:20:54 AM
VERBOSE: [AzureBridge:ActivateAzureBridge] Azure Environment: AzureCloud - 8/22/2017 1:20:54 AM
VERBOSE: [AzureBridge:ActivateAzureBridge] Deployment application config file: \\SU1FileServer\SU1_Infrastructure_1\ASResourceProvider\Confi
g\Deployment.IdentityApplication.Configuration.json - 8/22/2017 1:20:54 AM
WARNING: Task: Invocation of interface 'ActivateAzureBridge' of role 'Cloud\Fabric\AzureBridge' failed: 

Type 'ActivateAzureBridge' of Role 'AzureBridge' raised an exception:

Invalid path input: replace token not found. Path: 
at Get-SharePath, C:\CloudDeployment\Common\StorageHelpers.psm1: line 24
at ActivateAzureBridgeFeatures, C:\CloudDeployment\Roles\AzureBridge\AzureBridge.psm1: line 124
at ActivateAzureBridge, C:\CloudDeployment\Classes\AzureBridge\AzureBridge.psm1: line 172
at <ScriptBlock>, <No file>: line 18
at <ScriptBlock>, <No file>: line 16 - 8/22/2017 1:20:54 AM
C:\AzureStack-Tools-master\AzureStack-Tools-master\Registration\RegisterWithAzure.ps1 : Activate-Bridge: Error : System.Exception: Task: 
Invocation of interface 'ActivateAzureBridge' of role 'Cloud\Fabric\AzureBridge' failed: 
Type 'ActivateAzureBridge' of Role 'AzureBridge' raised an exception:
Invalid path input: replace token not found. Path: 
at Get-SharePath, C:\CloudDeployment\Common\StorageHelpers.psm1: line 24
at ActivateAzureBridgeFeatures, C:\CloudDeployment\Roles\AzureBridge\AzureBridge.psm1: line 124
at ActivateAzureBridge, C:\CloudDeployment\Classes\AzureBridge\AzureBridge.psm1: line 172
at <ScriptBlock>, <No file>: line 18
at <ScriptBlock>, <No file>: line 16 - 8/22/2017 1:20:54 AM
At line:1 char:1
+ .\RegisterWithAzure.ps1 -azureSubscriptionId "4e9319a5-1cf7-4099-80ea ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,RegisterWithAzure.ps1

**Comment by knithinc** [comment]
@BradleyBartlett could you please take a look at this issue?

**Comment by BradleyBartlett** [comment]
Hello @lilsaliu  can you confirm which branch you got the RegisterWithAzure script from and the version of Azure Stack you are using? 

You might be running into this due to an update in Azure Stack that requires a newer version of RegisterWithAzure.ps1

**Comment by lilsaliu** [comment]
@BradleyBartlett I work on master branch and Azure Stack Versison is  Prod_20170820.1_Staged, where is newer version of RegisterWithAzure.ps1, i can use?

**Comment by BradleyBartlett** [comment]
If you are using a newer version of Azure Stack you will need to use the RegisterWithAzure script from the VNext branch. We have not yet merged our changes into master as it is still undergoing some testing and changes. 

https://github.com/Azure/AzureStack-Tools/blob/vnext/Registration/RegisterWithAzure.ps1

There are a few differences in parameters. If you need help outside of the documentation in the script please feel free to email me.
