### ISSUE TITLE
Unregister-...

### ISSUE THREAD

**Issue by aricbernard** [Azure/AzureStack-Tools#317]
I am glad to see that both Register-AzsGuestDirectoryTenant and Register-AzsWithMyDirectoryTenant are working.  However, we have a scenario where in we need to UnRegister both (e.g. service provider is severing their relationship with an existing tenant).  How can this be done?

**Comment by kongou-ae** [comment]
I only comment about Register-AzsGuestDirectoryTenant.

AzsGuestDirectoryTenant adds DirectoryTenant to Azure Stack by using New-AzureRmResource. So if you want to delete directory tenant from Azure Stack, you can use Remove-AzureRmResource. You can check the resource id of directory tenant at the resource explorer.

**Comment by shriramnat** [comment]
@aricbernard we're working on a script to remove Azure Stack from the directory tenant. the other half of this as @kongou-ae mentioned is right. if either of you can propose a pull request with this we'll accept it. Let me know if you can work on this!
