### ISSUE TITLE
Missing parameter declaration in ServiceAdmin.psm1 in Master branch

### ISSUE THREAD

**Issue by leyasa** [Azure/AzureStack-Tools#355]
Line 142 on ServiceAdmin.psm1 branch is missing $ sign on variable 'ResourceGroupName' in parameter set declaration of Get-AzsServiceQuota.  Current snippet:
    param(
        [string] $ResourceName,
        [string] $ResourceType,
        [string] ResourceGroupName, <----Missing $ sign
        [string] $ApiVersion
    )

**Comment by knithinc** [comment]
@leyasa , thanks for reporting the issue. I fixed it.
