### ISSUE TITLE
[CloudCapabilities] The resulting JSON is not showing global locations since it's filtering on the wrong thing

### ISSUE THREAD

**Issue by JeffGoldner** [Azure/AzureStack-Tools#361]
On Azure Stack (haven't checked Azure), when a resource is applicable across locations, it will have a blank locations property, not "global".

$resourceTypes = (Get-AzureRmResourceProvider -ProviderNamespace $providerNamespace -ErrorAction Stop | Where-Object {$_.Locations -contains $location -or $_.Locations -contains "global"}).ResourceTypes

this will miss resources such as Authorization/locks.

**Comment by shriramnat** [comment]
fixed per checkin from Sumant
