### ISSUE TITLE
Test-AzureRMTemplate reports incorrect HTML file location.

### ISSUE THREAD

**Issue by deathly809** [Azure/AzureStack-Tools#367]
Test-AzureRMTemplate reports that:

```
Report available at - E:\github\AzureStack-Tools\TemplateValidator\Test.html
```

but it is actually located in the directory I executed the cmdlet.

There are two fixes, 

1.  Keep the HTML to placed at $Report and remove the variable $reportFilePath and use $Report
2.  Fix where to HTML is placed by using $reportFilePath variable instead of $Report variable.

A simple fix (which outputs into the TemplateValidator directory) should be to do the following:

```
245        ConvertTo-Html  $postContent -head $head -Body $reportHtml | out-File $Report
246    }
247    $reportFilePath = Join-Path $PSScriptRoot $Report
248    Write-Output "Validation Summary:
```

to

```
176    }
177    $reportFilePath = Join-Path $PSScriptRoot $Report
178    if (([System.IO.FileInfo]$Report).Extension -eq '.csv') {
...
245        ConvertTo-Html  $postContent -head $head -Body $reportHtml | out-File $reportFilePath
246    }
247    Write-Output "Validation Summary:
```

**Comment by knithinc** [comment]
@sumantshiv , could you please take a look at this issue?

**Comment by knithinc** [comment]
Fixed.
