### ISSUE TITLE
CreateGalleryItem

### ISSUE THREAD

**Issue by aricbernard** [Azure/AzureStack-Tools#368]
New-AzsServer2016VMImage is a useful tool especially for fully disconnected (isolated) environments.  This function has a dependency on CreateGalleryItem function.  Unfortunately, CreateGalleryItem requires the real time download of MarketplaceItem.zip even it has been previously downloaded or staged at the appropriate location.

Consider enabling this function for the fully disconnected scenario by allowing the MarketplaceItem.zip path to specified.

**Comment by shriramnat** [comment]
@MatthewMcGlynn  @troettinger  can you please take a look at this?

**Comment by knithinc** [comment]
This cmdlet has been deprecated. Closing issue at this time.
