### ISSUE TITLE
Remove-AzsVMImage silently fails to remove gallery item from marketplace

### ISSUE THREAD

**Issue by dsouzae** [Azure/AzureStack-Tools#376]
Hi,

I found that Remove-AzsVMImage does not remove the gallery image from the marketplace.  I found the following line of code [ComputeAdmin/AzureStack.ComputeAdmin.psm1#L387](https://github.com/Azure/AzureStack-Tools/blob/c76963b9d0cb1af83a600a437de942ace854b9dc/ComputeAdmin/AzureStack.ComputeAdmin.psm1#L387):

    `Get-AzsGalleryItem | Where-Object {$_.Name **-contains** "$publisher.$name.$version"} | Remove-AzsGalleryItem `

**-contains** should be **-like** in this case.  This works in my case, but not if it is the correct fix.

Another thing the code should probably should check it actually deleted an item as Remove-AszGalleryItem will not complain there is no object piped to it.

**Comment by knithinc** [comment]
This cmdlet has been moved to Azs.Compute.Admin module. Closing this issue.
