### ISSUE TITLE
New-AzsServer2016VMImage  should allow specification of SKU_Version

### ISSUE THREAD

**Issue by bottkars** [Azure/AzureStack-Tools#380]
#379 
New-AzsServer2016VMImage  should allow specification of SKU_Version
#379
Adding [version]$sku_version = (date -Format yyyy.MM.dd).ToString() to New-AzsServer2016VMImage to correctly that a Version for Server 2016 SKU other than 1.0.0
 Per default, I use (date -format yyMMdd) to tranlate the sku_version into a valid version string

**Comment by knithinc** [comment]
This cmdlet doesn't exist anymore. Closing the issue. Please file a new issue if there are any concerns.
