### ISSUE TITLE
[Add-AzsVMImage] "The pipeline was not run because a pipeline is already running" error

### ISSUE THREAD

**Issue by enihcam** [Azure/AzureStack-Tools#383]
Add-AzureRmVhd : The pipeline was not run because a pipeline is already running. Pipelines cannot
be run concurrently.
At F:\AzureStack-Tools-master\ComputeAdmin\AzureStack.ComputeAdmin.psm1:183 char:9
         Add-AzureRmVhd -Destination $osDiskBlobURIFromLocal -Resource ...
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo          : CloseError: (:) [Add-AzureRmVhd], PSInvalidOperationException
FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.StorageServices.AddAzureVhdCommand

The environment was clean and I didn't find any concurrent jobs running Add-AzsVMImage. Can you provide more details about "the pipeline"? which pipeline?

Thanks.

**Comment by enihcam** [comment]
duplicate with [4980](https://github.com/Azure/azure-powershell/issues/4980)

**Comment by marcvaneijk** [comment]
Thanks for the pointer to https://github.com/Azure/azure-powershell/issues/4980 we have opened the issue in the Azure module repo. Once it is fixed there, the issue for Azure Stack should be solved too.
