### ISSUE TITLE
Please publish the tools in nuget

### ISSUE THREAD

**Issue by enihcam** [Azure/AzureStack-Tools#384]
Because the link https://github.com/Azure/AzureStack-Tools/archive/master.zip is not always stable which sometimes breaks the deployment automation. It would be cool if this tools can be published in nuget. Thanks.

**Comment by marcvaneijk** [comment]
@enihcam do you mean that the connectivity to the content is not always stable or the content of the master branch?

**Comment by marcvaneijk** [comment]
Not active. Closing issue.
