### ISSUE TITLE
Sync-AzSOfflineMarketplaceItem execute error

### ISSUE THREAD

**Issue by patrickkuan** [Azure/AzureStack-Tools#386]
Hi,
I tried to execute the script as below after login Azure Account then got an error. 

PS C:\AzureStack-Tools-master\Syndication> Sync-AzSOfflineMarketplaceItem -destination c:\donwloadfolder -AzureTenantID
"bb044952-1248-4acb-a9b0-a29d37d4df79" -AzureSubscriptionID "949783b5-96a3-4b53-9053-2a731abab132"
不可在值為 Null 的運算式上呼叫方法。
位於 C:\AzureStack-Tools-master\Syndication\AzureStack.MarketplaceSyndication.psm1:44 字元:5
+     $tokens = [Microsoft.Azure.Commands.Common.Authentication.AzureSe ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) []，RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Invoke-RestMethod : {"error":{"code":"AuthenticationFailedMissingToken","message":"Authentication failed. The 'Authoriz
ation' header is missing the access token."}}
位於 C:\AzureStack-Tools-master\Syndication\AzureStack.MarketplaceSyndication.psm1:50 字元:18
+ ... products = (Invoke-RestMethod -Method GET -Uri $uri1 -Headers $Header ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod]，WebExce
    ption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by sirovermark** [comment]
Same problem here! AzS Tools downloaded today.

![image](https://user-images.githubusercontent.com/30412009/35801751-c8e7ec7e-0a6d-11e8-90d3-fd6981669e13.png)
