### ISSUE TITLE
Register-AzSGuestDirectoryTenant fail

### ISSUE THREAD

**Issue by patrickkuan** [Azure/AzureStack-Tools#387]
Hi
I followed the url https://github.com/Azure/AzureStack-Tools/tree/master/Identity  tried to enable multi-tenancy and got an error, there are the script(multi-nodes) and error message as below.(Our region name is set to 'twm')

I run the script on ASDK 1711 version both of single node and multi-nodes and got the same error.
My azure.rm version is 1.2.11 and azurestack-tools version is the last version.

PS C:\Windows\system32> cd C:\AzureStack-Tools-master
PS C:\AzureStack-Tools-master> Import-Module .\Connect\AzureStack.Connect.psm1
PS C:\AzureStack-Tools-master> Import-Module .\Identity\AzureStack.Identity.psm1
PS C:\AzureStack-Tools-master>
PS C:\AzureStack-Tools-master> $adminARMEndpoint = "https://adminmanagement.twm.freetrial.taiwancloud.com.tw"
PS C:\AzureStack-Tools-master>
PS C:\AzureStack-Tools-master> ## Replace the value below with the Azure Stack directory
PS C:\AzureStack-Tools-master> $azureStackDirectoryTenant = "taiwancloud.onmicrosoft.com"
PS C:\AzureStack-Tools-master> ## Replace the value below with the guest tenant directory.
PS C:\AzureStack-Tools-master> $guestDirectoryTenantToBeOnboarded = "azfreetry.onmicrosoft.com"
PS C:\AzureStack-Tools-master> $UserName='XXXXXXXXXX@taiwancloud.onmicrosoft.com'
PS C:\AzureStack-Tools-master> $Password='XXXXXXXXXX'| ConvertTo-SecureString -Force -AsPlainText
PS C:\AzureStack-Tools-master> $Cred=New-Object PSCredential($UserName,$Password)
PS C:\AzureStack-Tools-master>
PS C:\AzureStack-Tools-master>
PS C:\AzureStack-Tools-master>
PS C:\AzureStack-Tools-master> Register-AzSGuestDirectoryTenant -AdminResourceManagerEndpoint $adminARMEndpoint `
>>  -DirectoryTenantName $azureStackDirectoryTenant `
>>  -GuestDirectoryTenantName $guestDirectoryTenantToBeOnboarded `
>>  -Location "twm" `
>>  -ResourceGroupName 'system.twm' `
>>  -AutomationCredential $Cred
>>

output:
詳細資訊: GET https://adminmanagement.twm.freetrial.taiwancloud.com.tw/metadata/endpoints?api-version=2015-01-01 with
0-byte payload
詳細資訊: received 368-byte response of content type application/json; charset=utf-8
詳細資訊: Endpoints: {
    "galleryEndpoint":  "https://adminportal.twm.freetrial.taiwancloud.com.tw:30015/",
    "graphEndpoint":  "https://graph.windows.net/",
    "portalEndpoint":  "https://adminportal.twm.freetrial.taiwancloud.com.tw/",
    "authentication":  {
                           "loginEndpoint":  "https://login.windows.net/",
                           "audiences":  [

"https://adminmanagement.taiwancloud.onmicrosoft.com/e3bdc597-bbac-4fe1-b722-877d11773c50"
                                         ]
                       }
}
詳細資訊: GET https://login.windows.net/taiwancloud.onmicrosoft.com/.well-known/openid-configuration with 0-byte
payload
詳細資訊: received 1468-byte response of content type application/json; charset=utf-8
Add-AzureRmAccount : 值不能為 null。
參數名稱: uriString
位於 C:\AzureStack-Tools-master\Identity\AzureStack.Identity.psm1:200 字元:25
+         $azureAccount = Add-AzureRmAccount @params
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzureRmAccount]，ArgumentNullException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand

**Comment by leyasa** [comment]
Looks like the variable $ResourceManagerEndpoint is not being defined anywhere.

**Comment by yusukeMatsu** [comment]
Did you execute `Login-AzureRmAccount` before `Register-AzSGuestDirectoryTenant` ? To execute only `Register-AzSGuestDirectoryTenant` occured the same error in my asdk.

Could you try the following procedure before  `Register-AzSGuestDirectoryTenant`?
https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-powershell-configure-admin#configure-the-operator-environment-and-sign-in-to-azure-stack

**Comment by patrickkuan** [comment]
Thank you, If I run add-azurermenvironment  and named it to be  "azurestackadmin" first , The script  would be running successful!  So I think maybe the issue is cause of identity.psm1 doesn't provide the  parameter complete.

**Comment by keystroke** [comment]
This should be fixed with PR #403

**Comment by knithinc** [comment]
Fixed in PR #403
