### ISSUE TITLE
AzureStack-Tools / CanaryValidator / Canary.Tests.ps1 

### ISSUE THREAD

**Issue by pappleby64** [Azure/AzureStack-Tools#391]
If you run canary tests and change the exclusion list so that DeployARMTemplate is included it will fail.
The variable $osVersion on line 781 is null
It looks like some previous refactoring meant it was probably set correct at one point - but for now the only other references to $osVersion are local to the QueryImagesFromPIR test.
There are some lines commented out at 768 &769 which may been there and meant this worked - but those lines are not reliable as you really can't know what is in the PIR and so the index refs are guesswork.
suggest replicating part of the QueryImagesFromPIR code into the DeployARMTemplate to ensure this value gets set correctly

**Comment by knithinc** [comment]
Canary will be removed from Tools soon in favor of Test-AzureStack, so not much happening on this front. Will close this for now.
