### ISSUE TITLE
Remove-AzsRegistration deoes not work

### ISSUE THREAD

**Issue by slavizh** [Azure/AzureStack-Tools#400]
Cmdlet Remove-AzsRegistration  does not work. If you execute it the same steps for Add-AzsRegistration are executed meaning that it will fail because the resources are already created. Basically the problem is within RegistrationWorker function that is executing the creation of the registration before checking if ReturnRegistrationName is true.

**Comment by slavizh** [comment]
Just saw that this might be fixed in a updated version. Please close if you think it is fixed.

**Comment by marcvaneijk** [comment]
This issue should be fixed. Please report back if you still encounter the issue.

**Comment by Plutoniumn** [comment]
I have the same problem..
