### ISSUE TITLE
Sync-AzSOfflineMarketplaceItem  failure

### ISSUE THREAD

**Issue by pierrferr** [Azure/AzureStack-Tools#405]
In my case, Sync-AzSOfflineMarketplaceItem returns :

Invoke-RestMethod : {"error":{"code":"ParentResourceNotFound","message":"Can not perform requested operation 
on nested resource. Parent resource 'A' not found."}}
At C:\AzureStack-Tools-vnext\Syndication\AzureStack.MarketplaceSyndication.psm1:50 char:18
+ ... products = (Invoke-RestMethod -Method GET -Uri $uri1 -Headers $Header ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMetho 
   d], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCo 
   mmand

I have verified the prerequisites
- running powershell as admin
- AzureRM 1.2.11
- ASDK (version 20180103.2) is registered.
- I'm logged into Azure

What does this error means in my context ?

It points to an issue at these lines of the script :
 $uri1 = "$($azureEnvironment.ResourceManagerUrl.ToString().TrimEnd('/'))/subscriptions/$($AzureSubscriptionID.ToString())/resourceGroups/azurestack/providers/Microsoft.AzureStack/registrations/$($Registration.ToString())/products?api-version=2016-01-01"
    $Headers = @{ 'authorization'="Bearer $($Token.AccessToken)"} 
    $products = (Invoke-RestMethod -Method GET -Uri $uri1 -Headers $Headers).value

**Comment by pierrferr** [comment]
I resolved this by reinstalling from scratch. I had probably missed a dependency.

**Comment by marcvaneijk** [comment]
Good to hear the issue is solved.
