### ISSUE TITLE
Login-AzureRmAccount : AADSTS65005

### ISSUE THREAD

**Issue by ybping** [Azure/AzureStack-Tools#410]
If tenant is a multi tenant, Login-AzureRmAccount will fail:
AADSTS65005: Invalid resource. The client has requested access to a resource which is not
listed in the requested permissions in the client's application registration. Client app ID:
1950axxx-xxx-4e31-a9cf-xxxxxxx. 

The solution is specify your tenant id in the parameter, like this:
`Login-AzureRmAccount -EnvironmentName "AzureStackAdmin"  -TenantId {your-tenantId}`

hope the readme can update, thanks.

**Comment by troettinger** [comment]
Please validate the new published version which we have addressed the issue
