### ISSUE TITLE
Adding the [version]$osImageSkuVersion = (date -Format yyyy.MM.dd).ToString()

### ISSUE THREAD

**Issue by bottkars** [Azure/AzureStack-Tools#428]
this parameter set´an OS Image SKU Version to be different from the hardcoded 1.0.0

it is included in Pull request https://github.com/Azure/AzureStack-Tools/pull/427

Please review the changes. ALso included latest os patch

**Comment by knithinc** [comment]
The corresponding PR was merged, closing issue. Thanks.
