### ISSUE TITLE
Quota in plan - how to check the content of quota

### ISSUE THREAD

**Issue by sirmnemonic** [Azure/AzureStack-Tools#430]
Hi, 
how to check the content of already created quota (i.e.  compute)?
I want to know if I granted enough cores for the customer. 

Is it possible ?

Br,
Chris

**Comment by cblackuk** [comment]
@sirmnemonic 

I think you can try this -> https://docs.microsoft.com/en-us/powershell/module/azs.compute.admin/get-azscomputequota?view=azurestackps-1.3.0

```powershell
Get-AzsComputeQuota

AvailabilitySetCount : 5
CoresLimit           : 40
VirtualMachineCount  : 10
VmScaleSetCount      : 10
Id                   : /subscriptions/xxx-xxx-xxx-xxx-xxx-xxx-xxx/providers/Microsoft.Compute.Admin/locations/
                       xxxxxx/quotas/x-x-x-x-1-computedefault
Name                 : x-x-x-x-x-computedefault
Type                 : Microsoft.Compute.Admin/quotas
Location             : xxxxxxx
```

**Comment by sirmnemonic** [comment]
Thanks, but I receive an error:

Get-AzsComputeQuota : The term 'Get-AzsComputeQuota' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-AzsComputeQuota
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-AzsComputeQuota:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by yusukeMatsu** [comment]
Did you install PowerShell for Azure Stack 1.3.0 ?

https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-powershell-install#install-powershell-in-a-connected-scenario-with-internet-connectivity

**Comment by sirmnemonic** [comment]
Thanks guys for help. 
Upgrading PS to 1.3.0 helped.

**Comment by cblackuk** [comment]
@sirmnemonic  I am glad that it worked! Do you mind closing this down then? :-)

**Comment by knithinc** [comment]
Closing the issue since it is resolved.
