### ISSUE TITLE
module missing

### ISSUE THREAD

**Issue by giarbi** [Azure/AzureStack-Tools#438]
.\Infrastructure missing in the current brach

**Comment by OneCyrus** [comment]
Infrastructure was removed in PR #429. 

@troettinger is there a replacement for this? Or why was it removed?

**Comment by knithinc** [comment]
@OneCyrus , @giarbi , please use the AzureStack module version 1.3.0 from PowerShellGallery. Everything that has been removed from the Tools repo has a replacement in the new module, and it is consistent with the tenant experience.
More details @ 
https://docs.microsoft.com/en-us/powershell/azure/azure-stack/overview?view=azurestackps-1.3.0

Let us know if you find any issues using them.
