### ISSUE TITLE
Issue with RegisterWithAzure.psm1 when registering multiple Scale Units to a single subscription

### ISSUE THREAD

**Issue by ChrisMahon-DellEMC** [Azure/AzureStack-Tools#442]
Issue: Failure to register multiple Azure Stacks to a single CSP subscription
Error: New-AzureRmResource : CloudIdUpdateNotAllowed : The registration 'AzureStackRegistration' is already associated with another Cloud identifier. Changing cloud identifiers is not allowed.

Subscriptions > Providers > Microsoft.AzureStack > Registrations

This shows registration for AzureStackRegistration. Prior registrations had it in format "AzureStack-CloudID". It looks like "CloudID" is not being appended to the registration names anymore. We ended up utilizing an older version of the AzureStack-Tools to accomplish the registration for these multiple stacks.

Proof:
Line 192 | $RegistrationName = "AzureStackRegistration"

Prior version of tools had the following which worked: 
$RegistrationName = "AzureStack-$($stampinfo.CloudID)"

**Comment by BradleyBartlett** [comment]
This is because I removed the auto-naming of the registration resource in Azure to align with how other Azure Powershell cmdlets have a name as a required property. There is a default name but it is now generic and the name property is planned to become mandatory in the future. 

Were you able to successfully register your environments once you provided the correct registration resource name?

**Comment by ChrisMahon-DellEMC** [comment]
> This is because I removed the auto-naming of the registration resource in Azure to align with how other Azure Powershell cmdlets have a name as a required property. There is a default name but it is now generic and the name property is planned to become mandatory in the future.
> 
> Were you able to successfully register your environments once you provided the correct registration resource name?

Yes sir! We discovered we were missing a "-RegistrationName" parameter. The documentation had not been updated to reflect that yet, but we were able to see it as a documented parameter in the module. All is well!

**Comment by BradleyBartlett** [comment]
Excellent! Glad to hear it's been resolved. I'll close this issue.
