### ISSUE TITLE
Offline Syndication readme does not contain all required information 

### ISSUE THREAD

**Issue by JeffGoldner** [Azure/AzureStack-Tools#449]
The offline syndication tool creates a text file which contains the necessary parameters for importing items into the Azure Stack gallery and CRP. These parameters are critical and must be entered exactly or the items will not deploy.

**Comment by JeffGoldner** [comment]
Missing: reference to text file and parameters which are required and must be used exactly when uploading to PIR or GAR. Real examples and lots of warning about how these work and you can't choose random values.
Missing documentation of the -Cloud parameter. This works, just needs ta simple change.

**Comment by knithinc** [comment]
This has been updated.
