### ISSUE TITLE
While preparing the environemnt, if error:insufficient diskspace occurs the installer should not allow you to continue

### ISSUE THREAD

**Issue by efemmano** [Azure/AzureStack-Tools#450]
While preparing the environment to boot from cloudbuilder.vhdx, there is a disk space check. However even if there is insufficient disk space on the machine used, an error will appear on the UI installer but will allow you to click next and continue, only to fail deployment several hours later (attachment with error). When this error occurs the installer should not allow the user to continue.
![asdk_insufficient_diskspace](https://user-images.githubusercontent.com/16904423/44168545-7e4f7b00-a086-11e8-809d-e527e478a75e.png)

**Comment by marcvaneijk** [comment]
@efemmano, I'm unable to repro the issue. Just like in your screenshot the next button is greyed out in my environment once I hit the insufficient diskspace error. When I click on the button nothing happens (as expected). If you have an environment that allows you to continue (click next button) after the error is thrown, please share with me offline. Thanks, Marc

**Comment by marcvaneijk** [comment]
Closing. We can reopen if issue resurfaces.
