### ISSUE TITLE
Sync-AzSOfflineMarketplaceItem results in error

### ISSUE THREAD

**Issue by KRKandavel** [Azure/AzureStack-Tools#458]
Team, We are working with Reliance on Azure Stack project and have an issue in the offline marketplace download tool – Sync-AzSOfflineMarketplaceItem. Customer has raised a support ticket and sending this email after consulting with the support engineer.

At first, we had this error that says RG by name ‘azurestack’ is missing. I have checked in my subscription that is registered with AzureStack, and it had ‘azurestack’ resource group, whereas in the customer environment it was missing.

 

-	Customer created the ‘azurestack’ resource group in azure subscription registered with Azure Stack, but got the below error, and unable to find the cause for it, and need your help to understand the cause and solution for it.
-	Is it possible that the registration was not complete fully? Customer is able to download the marketplace items without problem using the Azure portal.

[Sync-AzSOfflineMarketplaceItem-Error.docx](https://github.com/Azure/AzureStack-Tools/files/2351410/Sync-AzSOfflineMarketplaceItem-Error.docx)

**Comment by bganapa** [comment]
azs.syndication.admin module has been released in powershell gallery to address many of the syndication issues
