### ISSUE TITLE
Need the compute admin folder in master branch

### ISSUE THREAD

**Issue by Arshuga** [Azure/AzureStack-Tools#467]
Hi 

We need the "**AzureStack.ComputeAdmin.psm1**" folder in the master branch. Need this file for 1808 version of Azure stack

We are getting the below error while pushing the iso image:

"Invoke-WebRequest : Could not find a part of the path 'C:\AzureStack-Tools-master\ComputeAdmin\update.msu'.
At C:\AzureStack-Tools-master\ComputeAdmin\AzureStack.ComputeAdmin.psm1:622 char:17
+ ...             Invoke-WebRequest -Uri $Uri -OutFile $OutFile -UseBasicPa ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand"

Please do let us know if this error is because of that file is missing or are we missing something else

**Comment by knithinc** [comment]
ComputeAdmin is now part of AzureStack module. You can download the AzureStack module from PSGallery, and the cmdlets you need should be available in Azs.Compute.Admin module. 
See this - https://docs.microsoft.com/en-us/powershell/azure/azure-stack/overview?view=azurestackps-1.5.0

Please let us know if that doesn't work. Closing this issue.

**Comment by Arshuga** [comment]
Hi,
Can I get the link to download Azure Stack tools for 1.5.0

I followed the link"https://github.com/Azure/AzureStack-Tools/archive/master.zip `  but i didn't find Azs.Compute.Admin in it .

**Comment by Arshuga** [comment]
> ComputeAdmin is now part of AzureStack module. You can download the AzureStack module from PSGallery, and the cmdlets you need should be available in Azs.Compute.Admin module.
> See this - https://docs.microsoft.com/en-us/powershell/azure/azure-stack/overview?view=azurestackps-1.5.0
> 
> Please let us know if that doesn't work. Closing this issue.

Hi,
Can I get the link to download Azure Stack tools for 1.5.0

I followed the link"https://github.com/Azure/AzureStack-Tools/archive/master.zip ` but i didn't find Azs.Compute.Admin in it .

**Comment by Arshuga** [comment]
Hi 
while uploading the windows server 2016 to azure stack I am getting this error
 "New-AzsServer2016VMImage `
  -ISOPath $ISOPath

New-AzsServer2016VMImage : The term 'New-AzsServer2016VMImage' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ New-AzsServer2016VMImage `
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-AzsServer2016VMImage:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException"
