### ISSUE TITLE
Unable to upload windows 2016 server image using "New-AzsServer2016VMImage "

### ISSUE THREAD

**Issue by Arshuga** [Azure/AzureStack-Tools#472]
Hi
while uploading the windows server 2016 to azure stack I am getting this error
"New-AzsServer2016VMImage `
-ISOPath $ISOPath

New-AzsServer2016VMImage : The term 'New-AzsServer2016VMImage' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1

New-AzsServer2016VMImage `
  + CategoryInfo          : ObjectNotFound: (New-AzsServer2016VMImage:String) [], CommandNotFoundException
  + FullyQualifiedErrorId : CommandNotFoundException"

Is this because of the Azs.compute.admin.psm1, I used "Import-module Azs.compute.admin.psm1" instead of "Import-Module .\ComputeAdmin\AzureStack.ComputeAdmin.psm1 " (since I didn't get this module with azure stack tools) 
 help me regarding this

**Comment by Arshuga** [comment]
Any updates please let us know as soon as possible, since we are working on production environment.

**Comment by knithinc** [comment]
@Arshuga , this cmdlet has been deprecated and you should be using the cmdlets exposed as part of Azs.Compute.Admin for all the image related actions on AzureStack. 
Please refer to these links:
https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-powershell-install
https://docs.microsoft.com/en-us/powershell/azure/azure-stack/overview?view=azurestackps-1.5.0

You are specifically looking for:
Add.AzsPlatformImage 
Refer: https://docs.microsoft.com/en-us/powershell/module/azs.compute.admin/Add-AzsPlatformImage?view=azurestackps-1.5.0

Please reach out to us or open a new issue if you are unable to use that cmdlet.

**Comment by knithinc** [comment]
Closing this issue at this time.
