### ISSUE TITLE
Installer fails without error on compressed drive

### ISSUE THREAD

**Issue by bjornbouetsmith** [Azure/AzureStack-Tools#474]
Hi,

Just tried installing the asdk on my server. Initially I had the CloudBuilder.vhdx on my c drive, but the installer complained that it was too small, so I copied it to my d drive which has ntfs compression enabled.

I then proceeded with the installation, went though the dialogs and was left with the option to reboot now or later.

I then rebooted, but windows started up normally, so I checked my boot.ini and it was unchanged.

I then digged into the installation script to see what it was doing and I could see that it mounts the virtual harddisk.

I tried manually to mount the harddisk and windows complained that it could not mount it since it was on a compressed drive.

So it seems like the installer somehow catches the error of the:
 $Prepare_Vhdx_Mounted = Mount-DiskImage -ImagePath $Prepare_Vhdx_Path -PassThru | Get-DiskImage | Get-Disk

and then fails to add anytning to the boot.ini

**Comment by bganapa** [comment]
not relevant for this repo , closing this as its too old
