### ISSUE TITLE
ASDK-installer: BGPNAT network settings not requested (Lenovo NIC drivers)

### ISSUE THREAD

**Issue by gijs007** [Azure/AzureStack-Tools#482]
I have two machines for testing: a Lenovo and a HP server.
This issue only happens on the Lenovo server, and only when the network drivers have been installed.

The issue is that the BGPNAT settings are not requested during the installation wizard, only the DNS forwarder and a proxy are requested.
After the installation the BGPNAT VM resorts to APIPA for IP address configuration. 

The strange thing is that this only happens if the network drivers for this particular Lenovo server are installed. The NIC itself, identified as a Broadcom NetXtreme, works fine with and without the drivers installed.

It's possible to manually execute the steps performed by the wizard, as a workaround:
1. Disable all NIC's, except the one used.
2. Specify the BGPNAT settings trough the command line and execute the script "manually".

**Comment by bganapa** [comment]
Not relevant for this repo
