### ISSUE TITLE
Remove-AzsActivationResource seems to fail in disconnected environment

### ISSUE THREAD

**Issue by dfencegit** [Azure/AzureStack-Tools#491]
Running remove-azsactivationenvironment appears to fail in a disconnected environment as the context environment is not configured with the correct ARM endpoints to logon.  This may be due to missing instructions in the docs but can be easily made more robust by allowing the code to work them out itself as it already has the stamp information required.  I lashed together a quick patch to demonstrate.  Replacing line 1012 with the following (diff file attached).

        # Azure Stack Stamp information from PEP session
        $AzureStackStampInfo = Invoke-Command -Session $session -ScriptBlock { Get-AzureStackStampInformation }

        # Create the Azure Stack Azure Resource Manager environment by using the following cmdlet:
        $ArmEndpointURL = $AzureStackStampInfo.AdminExternalEndpoints.AdminResourceManager
        $GraphAudienceURL = $ArmEndpointURL -replace "adminmanagement", "graph"
        Log-Output "Adding $ArmEndpointURL to the Environment $AzureEnvironmentName"
        Add-AzureRMEnvironment -Name "$AzureEnvironmentName" -ArmEndpoint $ArmEndpointURL
        Set-AzureRmEnvironment -Name "$AzureEnvironmentName" -GraphAudience $GraphAudienceURL -EnableAdfsAuthentication:$true

        # Login to stack

[RegisterWithAzure.txt](https://github.com/Azure/AzureStack-Tools/files/2754719/RegisterWithAzure.txt)

**Comment by rakku-ms** [comment]
PR: https://github.com/Azure/AzureStack-Tools/pull/528
