### ISSUE TITLE
When Trying to Register ASDK Deployment getting failure message (1904)

### ISSUE THREAD

**Issue by joseq-terawe** [Azure/AzureStack-Tools#509]
VERBOSE: 2019-05-27.13-36-21: Connection to AzS-ERCS01 successful
VERBOSE: 2019-05-27.13-36-21: Verifying stamp version.
VERBOSE: 2019-05-27.13-36-31: Running registration actions on build 1.1904.0.36. Cloud Id: xxxxxxxx
-xxxx-xxxx-xxxx-xxxxxxxxxxxx, Deployment Id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
VERBOSE: 2019-05-27.13-36-31: Creating Azure Active Directory service principal in tenant 'xxxxxxxx
-xxxx-xxxx-xxxx-xxxxxxxxxxxx' Attempt 0 of 3
VERBOSE: Looking up shared vhd product drive letter.
WARNING: Unable to find volume with label Deployment
VERBOSE: Get-Package returned with Success:True
VERBOSE: Found package Microsoft.AzureStack.Solution.Deploy.Security with version 1.1904.0.36 at C:
\NugetStore\Microsoft.AzureStack.Solution.Deploy.Security.1.1904.0.36\Microsoft.AzureStack.Solution
.Deploy.Security.nuspec.
VERBOSE: type added
VERBOSE: 2019-05-27.13-41-52: *** WARNING ***
WARNING: 2019-05-27.13-41-52: Creation of service principal failed:
Action plan execution failed. Error: Execution timeout
VERBOSE: 2019-05-27.13-52-36: *** End WARNING ***
VERBOSE: 2019-05-27.13-52-36: Waiting 10 seconds and trying again...
VERBOSE: 2019-05-27.13-52-46: ************************ Error ************************
VERBOSE: 2019-05-27.13-52-46: Action plan execution failed. Error: Execution timeout
VERBOSE: 2019-05-27.13-52-47: at Start-ActionPlanInstance, C:\Program Files\WindowsPowerShell\Modul
es\Microsoft.Azurestack.Activation\Microsoft.Azurestack.Activation.psm1: line 426
at New-AzureBridgeServicePrincipal, C:\Program Files\WindowsPowerShell\Modules\Microsoft.Azurestack
.Activation\Microsoft.Azurestack.Activation.psm1: line 179
VERBOSE: 2019-05-27.13-52-47: *********************** Ending registration action during New-Service
Principal ***********************
VERBOSE: 2019-05-27.13-52-47: Logs can be found at: C:\MASLogs\Registration\AzureStack.Activation.S
et-AzsRegistration-2019-05-27.log and \AzS-ERCS01\c$\maslogs
VERBOSE: 2019-05-27.13-52-47: Removing any existing PSSession...
Action plan execution failed. Error: Execution timeout
At C:\AzureStack-Tools-master\Registration\RegisterWithAzure.psm1:1249 char:13

        $servicePrincipal = Invoke-Command -Session $PSSession -S ...
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo : OperationStopped: (Action plan exe...ecution timeout:String) [], Ru
ntimeException
FullyQualifiedErrorId : Action plan execution failed. Error: Execution timeout

**Comment by TravisCragg-MSFT** [comment]
@joseq-terawe This is a known issue, and is being discussed [Here on the Azure Stack MSDN Forums.](https://social.msdn.microsoft.com/Forums/en-US/9e319e05-f498-4f75-a466-bf8593524395/cant-register-asdk-adfs-to-azure?forum=AzureStack)

> This issue is being caused due to an improper timeout on the service principal creation, and all we need to do is increase the timeout. 
> To mitigate this issue, you will need to open up the file at "C:\AzureStack-Tools-master\Registration/RegisterWithAzure.psm1" in an editor with ADMINISTRATOR PERMISSIONS, I prefer PowerShell ISE as it gives line numbers. 
> Line#1249 needs -TimeoutInSeconds 600 added to the "New-AzureBridgeServicePrincipal" cmdlet, and should look like this:
> $servicePrincipal = Invoke-Command -Session $PSSession -ScriptBlock { New-AzureBridgeServicePrincipal -RefreshToken $using:RefreshToken -AzureEnvironment $using:AzureEnvironmentName -TenantId $using:TenantId -TimeoutInSeconds 600}
> 
> We are fixing this in the Registration Script as well, but for now the manual workaround is the best.

**Comment by knithinc** [comment]
Fix for this has been merged. Please let us know if that doesn't resolve the problem.
