### ISSUE TITLE
Unregister-AzSGuestDirectoryTenant is always pointing to the Consumption Subscription

### ISSUE THREAD

**Issue by heoelri** [Azure/AzureStack-Tools#518]
When trying to Unregister-AzSGuestDirectoryTenant (updated 08/10/2019) to unregister a previously onboarded AAD Tenant Unregister-AzSGuestDirectoryTenant (updated 08/10/2019) is always pointing to the "Consumption Subscription" instead of using the SubscriptionName or SubscriptionID that is provided (in our Case the Default Provider Subscription).

**Comment by keystroke** [comment]
@heoelri Do you perhaps mean the command "Unregister-AzsGuestDirectoryTenant" and not the "Unregister-AzsWithMyDirectoryTenant" command? The latter doesn't reference any subscription and is actually run against the "public" or "tenant" ARM instance.

**Comment by heoelri** [comment]
@keystroke you are completely right. Good catch, I'm sorry. I'm talking about **Unregister-AzSGuestDirectoryTenant** (the one that's executed against the adminmanagement endpoint. I'll update the title.

**Comment by keystroke** [comment]
@heoelri Do you want to give the linked change a try and verify that it works for you?

**Comment by bganapa** [comment]
Closing this for non activity @heoelri pls feel free to reopen this , if needed
