### ISSUE TITLE
MSAssetTag

### ISSUE THREAD

**Issue by caaustin74** [Azure/AzureStack-Tools#538]
Having this error trying to register ASDK 1910. Previously had no issues using this powershell to register this same ASDK to the same subscription.

}
VERBOSE: 2019-12-14.19-54-37: Creating registration token. Attempt 0 of 3
VERBOSE: 2019-12-14.19-54-37: *** WARNING ***
WARNING: 2019-12-14.19-54-37: Creation of registration token failed:
A parameter cannot be found that matches parameter name 'MsAssetTag'.
VERBOSE: 2019-12-14.19-54-37: *** End WARNING ***
VERBOSE: 2019-12-14.19-54-37: Waiting 10 seconds and trying again...
VERBOSE: 2019-12-14.19-54-47: Creating registration token. Attempt 1 of 3
VERBOSE: 2019-12-14.19-54-47: *** WARNING ***
WARNING: 2019-12-14.19-54-47: Creation of registration token failed:
A parameter cannot be found that matches parameter name 'MsAssetTag'.
VERBOSE: 2019-12-14.19-54-47: *** End WARNING ***
VERBOSE: 2019-12-14.19-54-47: Waiting 10 seconds and trying again...
VERBOSE: 2019-12-14.19-54-58: Creating registration token. Attempt 2 of 3
VERBOSE: 2019-12-14.19-54-58: *** WARNING ***
WARNING: 2019-12-14.19-54-58: Creation of registration token failed:
A parameter cannot be found that matches parameter name 'MsAssetTag'.
VERBOSE: 2019-12-14.19-54-58: *** End WARNING ***
VERBOSE: 2019-12-14.19-54-58: Waiting 10 seconds and trying again...
VERBOSE: 2019-12-14.19-55-08: ************************ Error ************************
VERBOSE: 2019-12-14.19-55-08: A parameter cannot be found that matches parameter name 'MsAssetTag'.
VERBOSE: 2019-12-14.19-55-08: at Get-RegistrationToken, C:\AzureStack-Tools-master\Registration\RegisterWithAzure.psm1:
 line 1102
at Set-AzsRegistration, C:\AzureStack-Tools-master\Registration\RegisterWithAzure.psm1: line 240
at <ScriptBlock>, <No file>: line 1
VERBOSE: 2019-12-14.19-55-08: *********************** Ending registration action during Get-RegistrationToken
***********************
VERBOSE: 2019-12-14.19-55-08: Logs can be found at:
C:\MASLogs\Registration\AzureStack.Activation.Set-AzsRegistration-2019-12-14.log  and  \\\c$\maslogs
VERBOSE: 2019-12-14.19-55-08: Removing any existing PSSession...
A parameter cannot be found that matches parameter name 'MsAssetTag'.
At C:\AzureStack-Tools-master\Registration\RegisterWithAzure.psm1:1102 char:13
+             $registrationToken = Invoke-Command -Session $session -Sc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-RegistrationToken], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,New-RegistrationToken

**Comment by akn9050** [comment]
Confirmed, I also getting the same issue again and again, I tried in different Azure Subscription and tenants but no luck.

Error Message:
A parameter cannot be found that matches parameter name 'MsAssetTag'.
At C:\AzureStack-Tools-master\Registration\RegisterWithAzure.psm1:1102 char:13
+             $registrationToken = Invoke-Command -Session $session -Sc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-RegistrationToken], ParameterBindingExcep
   tion
    + FullyQualifiedErrorId : NamedParameterNotFound,New-RegistrationToken

**Comment by akn9050** [comment]
Hi @caaustin74,

I have resolved this issue in my repo, it is because of latest update in scripts.
You can use script from this repo:
https://github.com/akn9050/AzureStack-Tools/blob/master/Registration/RegisterWithAzure.psm1

**Comment by caaustin74** [comment]
Confirmed fix. Thank you for the modifications. I started to dive into the mods Saturday but ran out of time.

**Comment by rakku-ms** [comment]
PR with the fix: https://github.com/Azure/AzureStack-Tools/pull/542
